---
abstract: 'Receive Twitter streaming API in an event loop'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::Requires: 0
  Test::TCP: 0
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Twitter-Stream
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 2.0
  JSON: 2.0
  URI: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/AnyEvent-Twitter-Stream/issues
  homepage: https://github.com/miyagawa/AnyEvent-Twitter-Stream
  repository: https://github.com/miyagawa/AnyEvent-Twitter-Stream.git
version: 0.24
x_contributors:
  - 'Chris Prather <chris@prather.org>'
  - 'Daisuke Murase <typester@cpan.org>'
  - 'Marc Mims <marc@questright.com>'
  - 'Mark Norman Francis <norm@cackhanded.net>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'franck cuny <franck@lumberjaph.net>'
  - 'hidekiy <hideki.yamamura@gmail.com>'
  - 'megamic <megamic@cpan.org>'
  - 'punytan <punytan@gmail.com>'
